# Generated by Django 4.1.3 on 2022-11-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
